DEBUG 2019-04-22 12:29:33,824: 	 Executing command: 'submit'
DEBUG 2019-04-22 12:29:33,825: 	 Found CRAB cache file /user/jdeclerc/.crab3
DEBUG 2019-04-22 12:29:33,843: 	 Checking credentials
DEBUG 2019-04-22 12:29:33,844: 	 Found proxy file /tmp/x509up_u20641
DEBUG 2019-04-22 12:29:33,844: 	 Getting proxy life time left
DEBUG 2019-04-22 12:29:34,855: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -timeleft
 output : 43038

 error: 
 retcode : 0
DEBUG 2019-04-22 12:29:35,764: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -actimeleft
 output : 43037

 error: 
 retcode : 0
DEBUG 2019-04-22 12:29:35,765: 	 Proxy lifetime 43038 secs is different from voms extension lifetime 43037 secs for proxy: /tmp/x509up_u20641
DEBUG 2019-04-22 12:29:35,765: 	 Proxy valid for 11:57:17 hours
INFO 2019-04-22 12:29:35,765: 	 Will use CRAB configuration file crabConfig_AnalyzerAllSteps_step2.py
DEBUG 2019-04-22 12:29:35,766: 	 Loading CRAB configuration file.
DEBUG 2019-04-22 12:29:35,781: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-22 12:29:35,782: 	 Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaq_22042019_v1' already exists 
Please change the requestName in the config file
ERROR 2019-04-22 12:29:35,782: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaq_22042019_v1' already exists 
Please change the requestName in the config file
DEBUG 2019-04-22 13:38:43,867: 	 Executing command: 'submit'
DEBUG 2019-04-22 13:38:43,868: 	 Found CRAB cache file /user/jdeclerc/.crab3
DEBUG 2019-04-22 13:38:43,884: 	 Checking credentials
DEBUG 2019-04-22 13:38:43,885: 	 Found proxy file /tmp/x509up_u20641
DEBUG 2019-04-22 13:38:43,885: 	 Getting proxy life time left
DEBUG 2019-04-22 13:38:44,900: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -timeleft
 output : 38888

 error: 
 retcode : 0
DEBUG 2019-04-22 13:38:45,809: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -actimeleft
 output : 38887

 error: 
 retcode : 0
DEBUG 2019-04-22 13:38:45,809: 	 Proxy lifetime 38888 secs is different from voms extension lifetime 38887 secs for proxy: /tmp/x509up_u20641
DEBUG 2019-04-22 13:38:45,809: 	 Proxy valid for 10:48:07 hours
INFO 2019-04-22 13:38:45,810: 	 Will use CRAB configuration file crabConfig_AnalyzerAllSteps_skimmed.py
DEBUG 2019-04-22 13:38:45,811: 	 Loading CRAB configuration file.
DEBUG 2019-04-22 13:38:45,824: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-22 13:38:45,824: 	 Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaq_22042019_v1' already exists 
Please change the requestName in the config file
ERROR 2019-04-22 13:38:45,824: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaq_22042019_v1' already exists 
Please change the requestName in the config file
DEBUG 2019-04-22 13:43:06,087: 	 Executing command: 'submit'
DEBUG 2019-04-22 13:43:06,088: 	 Found CRAB cache file /user/jdeclerc/.crab3
DEBUG 2019-04-22 13:43:06,104: 	 Checking credentials
DEBUG 2019-04-22 13:43:06,105: 	 Found proxy file /tmp/x509up_u20641
DEBUG 2019-04-22 13:43:06,105: 	 Getting proxy life time left
DEBUG 2019-04-22 13:43:07,114: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -timeleft
 output : 38625

 error: 
 retcode : 0
DEBUG 2019-04-22 13:43:07,920: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -actimeleft
 output : 38625

 error: 
 retcode : 0
DEBUG 2019-04-22 13:43:07,921: 	 Proxy valid for 10:43:45 hours
ERROR 2019-04-22 13:43:07,922: 	 CRAB configuration file crab_AnalyzerAllStepsSexaq_22042019_v1 not found.
ERROR 2019-04-22 13:43:07,922: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 49, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crab_AnalyzerAllStepsSexaq_22042019_v1 not found.
DEBUG 2019-04-22 13:47:42,400: 	 Executing command: 'status'
DEBUG 2019-04-22 13:47:42,401: 	 Found CRAB cache file /user/jdeclerc/.crab3
DEBUG 2019-04-22 16:22:50,372: 	 Executing command: 'submit'
DEBUG 2019-04-22 16:22:50,372: 	 Found CRAB cache file /user/jdeclerc/.crab3
DEBUG 2019-04-22 16:22:50,501: 	 Checking credentials
DEBUG 2019-04-22 16:22:50,501: 	 Found proxy file /tmp/x509up_u20641
DEBUG 2019-04-22 16:22:50,501: 	 Getting proxy life time left
DEBUG 2019-04-22 16:22:51,511: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -timeleft
 output : 29041

 error: 
 retcode : 0
DEBUG 2019-04-22 16:22:52,422: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -actimeleft
 output : 29040

 error: 
 retcode : 0
DEBUG 2019-04-22 16:22:52,426: 	 Proxy lifetime 29041 secs is different from voms extension lifetime 29040 secs for proxy: /tmp/x509up_u20641
DEBUG 2019-04-22 16:22:52,427: 	 Proxy valid for 08:04:00 hours
INFO 2019-04-22 16:22:52,428: 	 Will use CRAB configuration file crabConfig_AnalyzerAllSteps_skimmed.py
DEBUG 2019-04-22 16:22:52,428: 	 Loading CRAB configuration file.
DEBUG 2019-04-22 16:22:52,434: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-22 16:22:52,434: 	 Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqSkimmed_22042019_v2' already exists 
Please change the requestName in the config file
ERROR 2019-04-22 16:22:52,434: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqSkimmed_22042019_v2' already exists 
Please change the requestName in the config file
DEBUG 2019-04-23 15:20:22,220: 	 Executing command: 'submit'
DEBUG 2019-04-23 15:20:22,220: 	 Found CRAB cache file /user/jdeclerc/.crab3
DEBUG 2019-04-23 15:20:22,234: 	 Checking credentials
DEBUG 2019-04-23 15:20:22,235: 	 Found proxy file /tmp/x509up_u20641
DEBUG 2019-04-23 15:20:22,235: 	 Getting proxy life time left
DEBUG 2019-04-23 15:20:23,345: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -timeleft
 output : 43192

 error: 
 retcode : 0
DEBUG 2019-04-23 15:20:24,152: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -actimeleft
 output : 43191

 error: 
 retcode : 0
DEBUG 2019-04-23 15:20:24,153: 	 Proxy lifetime 43192 secs is different from voms extension lifetime 43191 secs for proxy: /tmp/x509up_u20641
DEBUG 2019-04-23 15:20:24,153: 	 Proxy valid for 11:59:51 hours
INFO 2019-04-23 15:20:24,153: 	 Will use CRAB configuration file crabConfig_AnalyzerAllSteps_step2.py
DEBUG 2019-04-23 15:20:24,154: 	 Loading CRAB configuration file.
DEBUG 2019-04-23 15:20:24,165: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-23 15:20:24,165: 	 Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqStep2_23042019_v1' already exists 
Please change the requestName in the config file
ERROR 2019-04-23 15:20:24,165: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqStep2_23042019_v1' already exists 
Please change the requestName in the config file
DEBUG 2019-04-23 17:54:38,014: 	 Executing command: 'submit'
DEBUG 2019-04-23 17:54:38,014: 	 Found CRAB cache file /user/jdeclerc/.crab3
DEBUG 2019-04-23 17:54:38,030: 	 Checking credentials
DEBUG 2019-04-23 17:54:38,031: 	 Found proxy file /tmp/x509up_u20641
DEBUG 2019-04-23 17:54:38,031: 	 Getting proxy life time left
DEBUG 2019-04-23 17:54:39,040: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -timeleft
 output : 31218

 error: 
 retcode : 0
DEBUG 2019-04-23 17:54:40,048: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -actimeleft
 output : 31216

 error: 
 retcode : 0
DEBUG 2019-04-23 17:54:40,048: 	 Proxy lifetime 31218 secs is different from voms extension lifetime 31216 secs for proxy: /tmp/x509up_u20641
DEBUG 2019-04-23 17:54:40,048: 	 Proxy valid for 08:40:16 hours
INFO 2019-04-23 17:54:40,049: 	 Will use CRAB configuration file crabConfig_AnalyzerAllSteps_skimmed.py
DEBUG 2019-04-23 17:54:40,050: 	 Loading CRAB configuration file.
DEBUG 2019-04-23 17:54:40,074: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-23 17:54:40,075: 	 Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqSkimmed_23042019_v2' already exists 
Please change the requestName in the config file
ERROR 2019-04-23 17:54:40,075: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqSkimmed_23042019_v2' already exists 
Please change the requestName in the config file
DEBUG 2019-04-23 20:18:18,093: 	 Executing command: 'status'
DEBUG 2019-04-23 20:18:18,108: 	 Found CRAB cache file /user/jdeclerc/.crab3
DEBUG 2019-04-23 20:19:20,374: 	 Executing command: 'status'
DEBUG 2019-04-23 20:19:20,380: 	 Found CRAB cache file /user/jdeclerc/.crab3
ERROR 2019-04-23 20:19:20,416: 	 Error: /storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqSkimmed_23042019_v2 is not a valid CRAB project directory.
ERROR 2019-04-23 20:19:20,417: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 586, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: /storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqSkimmed_23042019_v2 is not a valid CRAB project directory.
DEBUG 2019-04-23 21:09:04,685: 	 Executing command: 'submit'
DEBUG 2019-04-23 21:09:04,689: 	 Found CRAB cache file /user/jdeclerc/.crab3
DEBUG 2019-04-23 21:09:04,718: 	 Checking credentials
DEBUG 2019-04-23 21:09:04,718: 	 Found proxy file /tmp/x509up_u20641
DEBUG 2019-04-23 21:09:04,718: 	 Getting proxy life time left
DEBUG 2019-04-23 21:09:05,423: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -timeleft
 output : 40247

 error: 
 retcode : 0
DEBUG 2019-04-23 21:09:06,028: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -actimeleft
 output : 40246

 error: 
 retcode : 0
DEBUG 2019-04-23 21:09:06,028: 	 Proxy lifetime 40247 secs is different from voms extension lifetime 40246 secs for proxy: /tmp/x509up_u20641
DEBUG 2019-04-23 21:09:06,028: 	 Proxy valid for 11:10:46 hours
INFO 2019-04-23 21:09:06,028: 	 Will use CRAB configuration file crabConfig_AnalyzerAllSteps_step2.py
DEBUG 2019-04-23 21:09:06,028: 	 Loading CRAB configuration file.
DEBUG 2019-04-23 21:09:06,060: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-23 21:09:06,061: 	 Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqStep2_23042019_v2' already exists 
Please change the requestName in the config file
ERROR 2019-04-23 21:09:06,061: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqStep2_23042019_v2' already exists 
Please change the requestName in the config file
DEBUG 2019-04-23 22:58:14,014: 	 Executing command: 'submit'
DEBUG 2019-04-23 22:58:14,052: 	 Found CRAB cache file /user/jdeclerc/.crab3
DEBUG 2019-04-25 20:37:04,167: 	 Executing command: 'submit'
DEBUG 2019-04-25 20:37:04,168: 	 Found CRAB cache file /user/jdeclerc/.crab3
DEBUG 2019-04-25 20:37:04,185: 	 Checking credentials
DEBUG 2019-04-25 20:37:04,185: 	 Found proxy file /tmp/x509up_u20641
DEBUG 2019-04-25 20:37:04,185: 	 Getting proxy life time left
DEBUG 2019-04-25 20:37:05,294: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -timeleft
 output : 42995

 error: 
 retcode : 0
DEBUG 2019-04-25 20:37:06,302: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u20641 -actimeleft
 output : 42994

 error: 
 retcode : 0
DEBUG 2019-04-25 20:37:06,302: 	 Proxy lifetime 42995 secs is different from voms extension lifetime 42994 secs for proxy: /tmp/x509up_u20641
DEBUG 2019-04-25 20:37:06,303: 	 Proxy valid for 11:56:34 hours
INFO 2019-04-25 20:37:06,303: 	 Will use CRAB configuration file crabConfig_AnalyzerAllSteps_skimmed.py
DEBUG 2019-04-25 20:37:06,303: 	 Loading CRAB configuration file.
DEBUG 2019-04-25 20:37:06,315: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-25 20:37:06,315: 	 Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqSkimmed_25042019_v1' already exists 
Please change the requestName in the config file
ERROR 2019-04-25 20:37:06,315: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 161, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1904/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/storage_mnt/storage/user/jdeclerc/Analysis/SexaQuark/CMSSW_9_4_7/src/SexaQAnalysis/AnalyzerAllSteps/test/crab/crab_AnalyzerAllStepsSexaqSkimmed_25042019_v1' already exists 
Please change the requestName in the config file
